// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate/db push/db execute) — Neon's pooled connection
    // doesn't support the schema-change advisory locks these need, so this
    // must be the *direct* (non "-pooler") connection string. The app's own
    // runtime PrismaClient (src/lib/db/client.ts) uses DATABASE_URL (pooled)
    // via its own adapter and never reads this file.
    url: process.env["DIRECT_URL"],
  },
});
